version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    groups:
      Cargo_Dependencies:
        patterns:
          - "*" # group all Rust dependencies together
    schedule:
      interval: weekly
