[package]
name = "mds-util"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mds-config.workspace = true
rlimit.workspace = true
log.workspace = true
console.workspace = true
pnet = "0.35.0"

[dev-dependencies]
rstest.workspace = true

[target.'cfg(windows)'.build-dependencies]
anyhow = "1.0.102"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls"] }
zip = "8.6.0"

[lints]
workspace = true
