name: 'Setup Npcap'
description: 'Download and configure Npcap SDK for Windows builds'

inputs:
  npcap-version:
    description: 'Version of Npcap SDK to install'
    required: true


runs:
  using: "composite"
  steps:
    - name: Download and extract Npcap SDK
      shell: bash
      run: |
        curl -L -o npcap-sdk.zip https://npcap.com/dist/npcap-sdk-${{ inputs.npcap-version }}.zip
        unzip npcap-sdk.zip -d npcap-sdk
        NPCAP_LIB=$(pwd)/npcap-sdk/Lib/x64
        NPCAP_INCLUDE=$(pwd)/npcap-sdk/Include
        echo "LIB=${NPCAP_LIB}" >> $GITHUB_ENV
        echo "INCLUDE=${NPCAP_INCLUDE}" >> $GITHUB_ENV
        echo "RUSTFLAGS=-L ${NPCAP_LIB}" >> $GITHUB_ENV

    - name: Install Npcap Runtime
      shell: pwsh
      run: |
        # Install Npcap runtime silently
        $version = "1.82"
        $exe = "npcap-runtime.exe"
        $url = "https://npcap.com/dist/npcap-$version.exe"
        Invoke-WebRequest -Uri $url -OutFile $exe
        Start-Process -FilePath ".\$exe" -ArgumentList "/S", "/winpcap_mode=yes" -Wait -NoNewWindow
