name: 'Setup Npcap'
description: 'Download and configure Npcap SDK for Windows builds'

inputs:
  npcap-version:
    description: 'Version of Npcap SDK to install'
    required: true


runs:
  using: "composite"
  steps:
    - name: Download and extract Npcap SDK
      shell: bash
      run: |
        curl -L -o npcap-sdk.zip https://npcap.com/dist/npcap-sdk-${{ inputs.npcap-version }}.zip
        unzip npcap-sdk.zip -d npcap-sdk
        NPCAP_LIB=$(pwd)/npcap-sdk/Lib/x64
        NPCAP_INCLUDE=$(pwd)/npcap-sdk/Include
        echo "LIB=${NPCAP_LIB}" >> $GITHUB_ENV
        echo "INCLUDE=${NPCAP_INCLUDE}" >> $GITHUB_ENV
        echo "RUSTFLAGS=-L ${NPCAP_LIB}" >> $GITHUB_ENV
