# Avoid linking with vcruntime140.dll by statically linking everything,
# and then explicitly linking with ucrtbase.dll dynamically.
# We do this, because vcruntime140.dll is an optional Windows component.
[target.'cfg(target_os = "windows")']
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Clink-args=/DEFAULTLIB:ucrt.lib",
    "-Clink-args=/NODEFAULTLIB:vcruntime.lib",
    "-Clink-args=/NODEFAULTLIB:msvcrt.lib",
    "-Clink-args=/NODEFAULTLIB:libucrt.lib",
]

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

# Works for RPI 4 & 5
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

# Works for RPI 0
[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]
