# mdns-scanner configuration file
#
# Possible Locations:
#
# Linux:
# - ~/.config/mdns-scanner/config.toml    (user-level)
# - ./mdns-scanner.toml                   (directory local)
#
# macOS:
# - ~/Library/Application Support/mdns-scanner/config.toml   (user-level)
# - ./mdns-scanner.toml                        (directory local)
#
# Windows:
# - %APPDATA%\mdns-scanner\config.toml         (user-level)
# - .\mdns-scanner.toml                        (directory local, relative to the executable)

[interfaces]
# Regex patterns to ignore network interfaces
# These patterns will be matched against interface names to exclude them from scanning
# NOTE: Common virtual interfaces are already excluded through the 'include_docker' setting
ignore_patterns = []

# Include docker network interfaces in scans
# By default, docker interfaces are excluded for cleaner results.
# Any interface with the following prefixes are excluded
# - veth
# - br-
# - podman
# - docker
include_docker = false


[scan]
# Enable DNS service discovery (DNS-SD)
# When enabled, attempts to discover services advertised via DNS-SD/mDNS
service_discovery = true

# TCP ports used to determine if a host is reachable at a given IP address.
# If a TCP connection can be established on any of these ports within
# the `tcp_port_ms` duration, the host is considered to be up.
# TIP: For port descriptions see: <https://www.speedguide.net/ports_common.php>
tcp_ports = [22, 80, 443]

# Number of I/O threads used for network scanning.
# Each I/O thread is responsible for opening a network socket. If multiple network
# interfaces are detected, the total number of threads is distributed evenly among them.
# Valid values:
# - 'dynamic': (Default) Queries system resources before each scan and adjusts the
# thread count based on CPU availability and system load.
# - Range 32-8192: A fixed number of I/O threads will be used for every scan.
# NOTE: This is not a global thread limit. It only constrains the number of
# threads performing network I/O.
io_threads = "dynamic"


[timeouts]
# How long to wait for TCP connection attempts
# This timeout applies to each port individually
# Range: 1-6535
tcp_port_ms = 100

# How long to wait for ping/echo replies
# Range: 1-6535
ping_ms = 300

# Upper time limit for checking if a host is up on an IP address
# This is the total timeout for all host-up detection methods combined
# Range: 1-6535
ip_check_ms = 5000


[ui]
# Use compact output format
# Hides help footer
compact = false

# Hide IPs with no association (no resolved hostname/service information)
hide_bare_ips = false

# Maximum number of logs to store in the buffer before logs are dropped
# Range 1-4294967295
log_limit = 1000
