# mdns-scanner keymap file
#
# Possible Locations:
#
# Linux:
# - ~/.config/mdns-scanner/keymap.toml    (user-level)
#
# macOS:
# - ~/Library/Application Support/mdns-scanner/keymap.toml   (user-level)
#
# Windows:
# - %APPDATA%\mdns-scanner\keymap.toml         (user-level)


[Global]
# Application
"<q>"   = "quit"
"<esc>" = "close"
"?"     = "keybindings"

# Navigation - Arrows
"<up>"    = "navigate-up"
"<down>"  = "navigate-down"
"<left>"  = "navigate-left"
"<right>" = "navigate-right"

# Navigation - Vim keys
"<k>" = "navigate-up"
"<j>" = "navigate-down"
"<h>" = "navigate-left"
"<l>" = "navigate-right"

# Navigation - Other
"<pageup>"   = "navigate-pageup"
"<pagedown>" = "navigate-pagedown"
"<home>"     = "navigate-scroll-to-beginning"
"<end>"      = "navigate-scroll-to-end"
"<space>"    = "navigate-select"
"<enter>"    = "navigate-select"

# Layout
"<tab>" = "toggle-focus"
"<+>"   = "increase-layout-fill"
"<->"   = "decrease-layout-fill"

# Clipboard
"<y>"            = "copy-to-clipboard"
"<ctrl-c>"       = "copy-to-clipboard"
"<ctrl-shift-c>" = "copy-to-clipboard"

# Other Actions
"<ctrl-r>" = "refresh"
"<ctrl-f>" = "search"
"<shift-c>" = "config"
"<ctrl-s>"  = "save-config"

# Logging verbosity
"<v>" = "increase-verbosity"
"<g>" = "decrease-verbosity"
