name: CI

on:
    pull_request:
    push:
        branches: [trunk]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2

        - name: Clippy
          run: cargo clippy --all-targets

        - name: Format
          run: cargo fmt --all -- --check

    audit:
        runs-on: ubuntu-latest
        env:
            RUST_LOG: '' # Otherwise audit-check errors on attempting to parse the logging output
        steps:
        - uses: actions/checkout@v4
        - name: Install cargo-binstall
          uses: cargo-bins/cargo-binstall@v1.12.3
        - name: Install Cargo audit
          run: cargo binstall cargo-audit
        - name: Run Audit
          run: cargo audit

    build-linux-musl:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                target:
                    - x86_64-unknown-linux-musl
                    - aarch64-unknown-linux-musl
                    - arm-unknown-linux-musleabihf
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: mlugg/setup-zig@v1
        - uses: Swatinem/rust-cache@v2

        - name: Install ZigBuild
          run: cargo install cargo-zigbuild --locked 

        - name: Install target
          run: rustup target add ${{ matrix.target }}

        - name: build
          run: |
            cargo zigbuild --bin mdns-scanner --target ${{ matrix.target }} --release

    build-windows:
        runs-on: windows-latest
        env:
            NPCAP_VER: 1.15
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2

            - name: Download and extract Npcap SDK
              shell: bash
              run: |
                curl -L -o npcap-sdk.zip https://npcap.com/dist/npcap-sdk-${{ env.NPCAP_VER }}.zip
                unzip npcap-sdk.zip -d npcap-sdk

            - name: Set environment for Npcap
              shell: bash
              run: |
                NPCAP_LIB=$(pwd)/npcap-sdk/Lib
                NPCAP_INCLUDE=$(pwd)/npcap-sdk/Include
                echo "LIB=${NPCAP_LIB}" >> $GITHUB_ENV
                echo "INCLUDE=${NPCAP_INCLUDE}" >> $GITHUB_ENV
                echo "RUSTFLAGS=-L ${NPCAP_LIB}" >> $GITHUB_ENV

            - name: Build
              shell: bash
              run: |
                echo "RUSTFLAGS=${RUSTFLAGS}"
                cargo build --release

    build-macos:
        runs-on: macos-latest
        strategy: 
            fail-fast: false
            matrix:
                target:
                    - aarch64-apple-darwin
                    - x86_64-apple-darwin
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2


            - run: rustup target add ${{ matrix.target }}
            - name: Build
              run: cargo build --release --target=${{ matrix.target }}
