name: CI

on:
    pull_request:
    push:
        branches: [trunk]

defaults:
    run:
        shell: bash

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2

        - name: Clippy
          run: cargo clippy --all-targets

        - name: Format
          run: cargo fmt --all -- --check

    audit:
        runs-on: ubuntu-latest
        env:
            RUST_LOG: '' # Otherwise audit-check errors on attempting to parse the logging output
        steps:
        - uses: actions/checkout@v4
        - name: Install cargo-binstall
          uses: cargo-bins/cargo-binstall@v1.12.3
        - name: Install Cargo audit
          run: cargo binstall cargo-audit
        - name: Run Audit
          run: cargo audit

    prerelease:
        runs-on: ubuntu-latest

        outputs:
            value: ${{ steps.prerelease.outputs.value }}
        steps:
            - name: Prerelease Check
              id: prerelease
              run: |
                if [[ ${{ github.ref_name }} =~ ^[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
                    echo value=false >> $GITHUB_OUTPUT
                else
                    echo value=true >> $GITHUB_OUTPUT
                fi

    build-package:
        strategy:
            matrix:
                target:
                    - aarch64-apple-darwin
                    - aarch64-unknown-linux-musl
                    - arm-unknown-linux-musleabihf
                    - armv7-unknown-linux-musleabihf
                    - x86_64-apple-darwin
                    - x86_64-pc-windows-msvc
                    # It might be possible to support this by excluding npcap for this target specifically
                    # - aarch64-pc-windows-msvc
                    - x86_64-unknown-linux-musl
                include:
                    - target: aarch64-apple-darwin
                      os: macos-latest
                      target_rustflags: ''
                    - target: aarch64-unknown-linux-musl
                      os: ubuntu-latest
                      target_rustflags: '--codegen linker=aarch64-linux-gnu-gcc'
                    - target: arm-unknown-linux-musleabihf
                      os: ubuntu-latest
                      target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
                    - target: armv7-unknown-linux-musleabihf
                      os: ubuntu-latest
                      target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
                    - target: x86_64-apple-darwin
                      os: macos-latest
                      target_rustflags: ''
                    - target: x86_64-pc-windows-msvc
                      os: windows-latest
                    # - target: aarch64-pc-windows-msvc
                    #   os: windows-latest
                    #   target_rustflags: ''
                    - target: x86_64-unknown-linux-musl
                      os: ubuntu-latest
                      target_rustflags: ''

        runs-on: ${{matrix.os}}
        needs:
            - prerelease

        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                targets: ${{ matrix.target }}

            - name: Install AArch64 Toolchain
              if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
              run: |
                sudo apt-get update
                sudo apt-get install gcc-aarch64-linux-gnu libc6-dev-i386

            - name: Install ARM Toolchain
              if: ${{ matrix.target == 'arm-unknown-linux-musleabihf' || matrix.target == 'armv7-unknown-linux-musleabihf' }}
              run: |
                sudo apt-get update
                sudo apt-get install gcc-arm-linux-gnueabihf

            - name: Download and extract Npcap SDK
              if: ${{ matrix.target == 'aarch64-pc-windows-msvc' || matrix.target == 'x86_64-pc-windows-msvc' }}
              env:
                NPCAP_VER: 1.15
              run: |
                curl -L -o npcap-sdk.zip https://npcap.com/dist/npcap-sdk-${{ env.NPCAP_VER }}.zip
                unzip npcap-sdk.zip -d npcap-sdk
                NPCAP_LIB=$(pwd)/npcap-sdk/Lib
                NPCAP_INCLUDE=$(pwd)/npcap-sdk/Include
                echo "LIB=${NPCAP_LIB}" >> $GITHUB_ENV
                echo "INCLUDE=${NPCAP_INCLUDE}" >> $GITHUB_ENV
                echo "RUSTFLAGS=-L ${NPCAP_LIB}" >> $GITHUB_ENV

            - uses: Swatinem/rust-cache@v2
              with:
                key: ${{ matrix.target }}

            - name: Package
              id: package
              env:
                  TARGET: ${{ matrix.target }}
                  REF: ${{ github.ref }}
                  OS: ${{ matrix.os }}
                  TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
              run: |
                export TARGET_RUSTFLAGS="${RUSTFLAGS} ${{ env.TARGET_RUSTFLAGS }}"
                ./scripts/package.bash

            - name: Publish Archive
              uses: softprops/action-gh-release@v2.2.1
              with:
                draft: ${{ startsWith(github.ref, 'refs/heads/trunk') }}
                files: ${{ steps.package.outputs.archive }}
                prerelease: ${{ needs.prerelease.outputs.value }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish Changelog
              uses: softprops/action-gh-release@v2.2.1
              if: >-
                ${{
                    startsWith(github.ref, 'refs/tags/')
                    && matrix.target == 'x86_64-unknown-linux-musl'
                }}
              with:
                draft: false
                files: CHANGELOG.md
                prerelease: ${{ needs.prerelease.outputs.value }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}